# Generated by Django 6.0.6 on 2026-06-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cashregister_courier_ingredient_orderchannel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bidolu Restoran', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_office', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('working_hours', models.CharField(default='09:00 - 23:00', max_length=100)),
                ('active_plan', models.CharField(default='Growth', max_length=50)),
                ('plan_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
