# Generated by Django 6.0.6 on 2026-06-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_banner_text',
            field=models.CharField(default='Hoş Geldiniz!', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_enable_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_enable_table_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_enable_takeaway',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_slug',
            field=models.CharField(default='bidolu-restoran', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_theme_color',
            field=models.CharField(default='#6366f1', max_length=30),
        ),
    ]
