# Generated by Django 6.0.6 on 2026-06-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurantprofile_website_banner_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_enable_reservation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website_template',
            field=models.CharField(default='Modern Dark', max_length=50),
        ),
    ]
