# Generated by Django 6.0.6 on 2026-06-06 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurantprofile_website_about_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('total_variance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.cashregister')),
            ],
        ),
        migrations.CreateModel(
            name='StockAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.stockaudit')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
            ],
        ),
    ]
