# Generated by Django 6.0.6 on 2026-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stockaudit_ingredient_unit_price_cashtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('last_order_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_auto_message_enabled', models.BooleanField(default=False)),
                ('message_template', models.TextField(default='Merhaba {customer_name}, {order_id} nolu siparişiniz alınmıştır. Afiyet olsun!')),
            ],
        ),
    ]
