# Generated by Django 6.0.6 on 2026-06-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_whatsappconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='ext_crm_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='ext_official_website_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='ext_qr_menu_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='ext_whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
