# Generated by Django 6.0.6 on 2026-06-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_restaurantprofile_ext_crm_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='ask_admin_before_sending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='is_live_chat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='is_auto_message_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
