# Generated by Django 6.0.6 on 2026-06-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_whatsappconfig_ask_admin_before_sending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='ext_live_courier_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
