# Generated by Django 6.0.6 on 2026-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restaurantprofile_ext_live_courier_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
