# Generated by Django 6.0.6 on 2026-06-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='api.brand'),
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.brand'),
        ),
        migrations.AddField(
            model_name='courier',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='api.brand'),
        ),
        migrations.AddField(
            model_name='customer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.brand'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.brand'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.brand'),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.brand'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='api.brand'),
        ),
        migrations.AddField(
            model_name='table',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.brand'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='api.brand'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together={('brand', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('brand', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('brand', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('brand', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('brand', 'name')},
        ),
    ]
