# Generated by Django 6.0.6 on 2026-06-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cashregister_brand_category_brand_courier_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('store_owner', 'Mağaza Sahibi'), ('manager', 'Müdür'), ('waiter', 'Garson'), ('cashier', 'Kasiyer'), ('kitchen', 'Mutfak')], default='waiter', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Süper Yönetici'), ('store_owner', 'Mağaza Sahibi'), ('manager', 'Müdür'), ('waiter', 'Garson'), ('cashier', 'Kasiyer'), ('kitchen', 'Mutfak')], default='waiter', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.brand')),
            ],
        ),
    ]
